# Generated by Django 4.0.1 on 2022-01-26 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descreption', models.CharField(max_length=100, verbose_name='Descreption of the state')),
                ('initials', models.CharField(max_length=100, verbose_name='Initials of the state ')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'ordering': ['descreption'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descreption', models.CharField(max_length=100, verbose_name='Descreption of the state')),
                ('initials', models.CharField(max_length=100, verbose_name='Initials of the state ')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CountryOfTheState', to='base.country')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'ordering': ['descreption'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descreption', models.CharField(max_length=100, verbose_name='Descreption of the City')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
                ('state', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='StateOfCity', to='base.state')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Citys',
                'ordering': ['descreption'],
            },
        ),
    ]
